root ::= "(define-fun f ((_arg_0 String)) String " Start ")"
Start ::= ntString
ntString ::= "_arg_0" | "" | " " | ""US CAN"" | "(" "str.++" " " ntString " " ntString ")" | "(" "str.replace" " " ntString " " ntString " " ntString ")" | "(" "str.at" " " ntString " " ntInt ")" | "(" "int.to.str" " " ntInt ")" | "(" "ite" " " ntBool " " ntString " " ntString ")" | "(" "str.substr" " " ntString " " ntInt " " ntInt ")"
ntInt ::= "1" | "0" | "-1" | "(" "+" " " ntInt " " ntInt ")" | "(" "-" " " ntInt " " ntInt ")" | "(" "str.len" " " ntString ")" | "(" "str.to.int" " " ntString ")" | "(" "ite" " " ntBool " " ntInt " " ntInt ")" | "(" "str.indexof" " " ntString " " ntString " " ntInt ")"
ntBool ::= "true" | "false" | "(" "=" " " ntInt " " ntInt ")" | "(" "str.prefixof" " " ntString " " ntString ")" | "(" "str.suffixof" " " ntString " " ntString ")" | "(" "str.contains" " " ntString " " ntString ")"

