root ::= Start ")"
Start ::= "(and " Depth1 " " Depth1 ")" | "(not " Depth1 ")" | "(or " Depth1 " " Depth1 ")" | "(xor " Depth1 " " Depth1 ")"
Depth1 ::= "(and " Depth2 " " Depth2 ")" | "(not " Depth2 ")" | "(or " Depth2 " " Depth2 ")" | "(xor " Depth2 " " Depth2 ")" | "LN3"
Depth2 ::= "(and " Depth3 " " Depth3 ")" | "(not " Depth3 ")" | "(or " Depth3 " " Depth3 ")" | "(xor " Depth3 " " Depth3 ")" | "LN29"
Depth3 ::= "(and " Depth4 " " Depth4 ")" | "(not " Depth4 ")" | "(or " Depth4 " " Depth4 ")" | "(xor " Depth4 " " Depth4 ")" | "LN19"
Depth4 ::= "LN20"