root ::= "define-fun f ((x (BitVec 64))) (BitVec 64) " start
start ::= "#x0000000000000000" | "#x0000000000000001" | "x" | NotOp | SmolOp | EhadOp | ArbaOp | SheshOp | AndOp | OrOp | XorOp | AddOp | ImOp
NotOp ::= "(bvnot " start ")"
SmolOp ::= "(smol " start ")"
EhadOp ::= "(ehad " start ")"
ArbaOp ::= "(arba " start ")"
SheshOp ::= "(shesh " start ")"
AndOp ::= "(bvand " start " " start ")"
OrOp ::= "(bvor " start " " start ")"
XorOp ::= "(bvxor " start " " start ")"
AddOp ::= "(bvadd " start " " start ")"
ImOp ::= "(im " start " " start " " start ")"
